services:

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app.db:/code/app.db
    environment:
      - DATABASE_URL=sqlite:///./app.db
    restart: unless-stopped
